# @format
services:
  - type: web
    name: apigateway
    runtime: docker
    plan: free
    dockerfilePath: ./apigateway/Dockerfile

  - type: web
    name: departmentservice
    runtime: docker
    plan: free
    dockerfilePath: ./departmentservice/Dockerfile

  - type: web
    name: employeeservice
    runtime: docker
    plan: free
    dockerfilePath: ./employeeservice/Dockerfile

  - type: web
    name: projectassignmentservice
    runtime: docker
    plan: free
    dockerfilePath: ./projectassignmentservice/Dockerfile

  - type: web
    name: serviceregistry
    runtime: docker
    plan: free
    dockerfilePath: ./serviceregistry/Dockerfile
